# ✅ Proxy للاتصال مع Google Apps Script
[[redirects]]
  from = "/api/*"
  to = "https://script.google.com/macros/s/AKfycbwqd_Ze2vqdA0Fv_mWa-u7TzR_GI_qgXBXl9zqWixo4J6SgpmXxXE9kWd75kylpmA/exec/:splat"
  status = 200
  force = true

# ✅ إعادة توجيه الصفحة الرئيسية إلى home.html
[[redirects]]
  from = "/"
  to = "/home.html"
  status = 200
  force = true
